### ISSUE TITLE
v1.7.1

### ISSUE THREAD

**Issue by JeffreyFalgout** [allangood/rtlamr2mqtt#109]
I don't think https://github.com/allangood/rtlamr2mqtt/issues/105 is fixed yet for add-on users since that bug fix was never pushed to the docker repo. Would it be possible to push the bug fix?

**Comment by allangood** [comment]
Just pushed a few changes and we are ready to test version 1.7.1 #112 
Thank you again @JeffreyFalgout

**Comment by JeffreyFalgout** [comment]
I updated my home assistant to use v1.7.1 and haven't noticed any issues yet. I'll file a new bug if I find any. Thanks!
