### ISSUE TITLE
Mismatched Paren

### ISSUE THREAD

**Issue by sradner13** [allangood/rtlamr2mqtt#11]
This has been going strong for me for many months, still love the work.  Latest update caused a little hiccup.

From the logs:

  File "/usr/bin/rtlamr2mqtt.py", line 86
    config['meters'][idx]['name'] = str(meter.get('name', 'meter_{}'.format(meter['id']))
                                                         ^
SyntaxError: '(' was never closed

Adding one trailing paren seems to fix it all up.

**Comment by allangood** [comment]
Hi @sradner13 ,

I am working to setup Travis to prevent this kind of error to happen in the future.

Thank you for your feedback!

**Comment by allangood** [comment]
Fixed in #13
