### ISSUE TITLE
Add-on support for arm64

### ISSUE THREAD

**Issue by toddq** [allangood/rtlamr2mqtt#121]
HA says the add-on is not compatible with my processor.  I see that the Docker image build includes arm64, should the add-on config's `arch` be updated to include arm64 as well?  Or is there a reason that it wouldn't actually be suported?

**Comment by allangood** [comment]
Hi @toddq , you are absolutely right, I should add this architecture to the supported list.
Thank you!

**Comment by allangood** [comment]
For reference, these are the supported (by github actions) platforms now:
`platforms: linux/amd64,linux/i386,linux/arm64,linux/arm/v7,linux/arm/v6`

**Comment by makeitworktech** [comment]
I think I'm having the same problem - is this fixable?

`22-04-29 16:59:33 WARNING (SyncWorker_4) [supervisor.store.data] Can't read /data/addons/git/6713e36e/rtlamr2mqtt-addon/config.json: value must be one of ['aarch64', 'amd64', 'armhf', 'armv7', 'i386'] @ data['arch'][3]. Got 'armv6'
value must be one of ['aarch64', 'amd64', 'armhf', 'armv7', 'i386'] @ data['arch'][4]. Got 'arm64'`

**Comment by karepiu** [comment]
Exactly same here. Trying add-on rpi3 and same error as above

**Comment by allangood** [comment]
I have added the wrong arch name: `arm64` instead of `aarch64` what caused this error.
Last commit fixed it.

Thank you for reporting!

**Comment by toddq** [comment]
Thanks!  One remaining thing is to update the badge in the add-on Readme.  It's still reporting no aarch64, which will be confusing.

**Comment by allangood** [comment]
Thank you for all your feedback and help!
