### ISSUE TITLE
example in readme not working

### ISSUE THREAD

**Issue by bmcgair** [allangood/rtlamr2mqtt#136]
docker run --rm -ti -e LISTEN_ONLY=yes -e RTL_MSGTYPE="all" --device=/dev/bus/usb:/dev/bus/usb allangood/rtlamr2mqtt
Traceback (most recent call last):
  File "/usr/bin/rtlamr2mqtt.py", line 38, in <module>
    log_message('Starting in LISTEN ONLY Mode...')
NameError: name 'log_message' is not defined

**Comment by allangood** [comment]
I am making some changes in the listen only mode.
Please, take a look at https://github.com/allangood/rtlamr2mqtt/discussions/133

Sorry for the inconvenience.

**Comment by allangood** [comment]
Fixed on #137
