### ISSUE TITLE
Feature Request: Add Force Update and Expires After options to Discovery

### ISSUE THREAD

**Issue by shbatm** [allangood/rtlamr2mqtt#148]
First, thank you for packaging this up as an add-on and Docker container. I'm trying to move to this from my stand-alone Python script that was updated from the original `amridm2mqtt` scripts.

I was hoping you could add support for the [`force_update`](https://www.home-assistant.io/integrations/sensor.mqtt/#force_update) and [`expire_after`](https://www.home-assistant.io/integrations/sensor.mqtt/#expire_after) options in discovery? I use these to make sure the sensors are still updating even if there is no usage for a while (e.g. while I'm away from the house and there is no water or gas usage). These make sure each MQTT message is recorded as a state update and if nothing new is received in X seconds (I use 3600) then it marks the state as unknown and I can trigger an automation to restart the script.

**Comment by allangood** [comment]
Hello @shbatm ,
the `force_update` is a good addition, but the `expire_after` may introduce problems.

Some meters send a new reading just when the utility company truck pass close by, or some send updates once in awhile on irregular intervals.

Thank you for you feedback!

**Comment by shbatm** [comment]
I would suggest making these config options and/or per meter.

**Comment by allangood** [comment]
The `force_update` parameters has been added on #151, the `expire_after` I would like to think in a good way on how to implementing it without a new user parameter.

**Comment by shbatm** [comment]
Sounds good. Looks like the 20yr battery must have died on my water meter since it's no longer transmitting so it'll be a while before I need the `expire_after`.
