### ISSUE TITLE
Home assistant add-on install error

### ISSUE THREAD

**Issue by dennis-ashworth** [allangood/rtlamr2mqtt#164]
My home assistant version info:
Home Assistant 2022.10.4
Supervisor 2022.10.0
Frontend 20221010.0 - latest 

Running on raspberry pi 4. 

Received the following error when I click install, after adding it to HA add-ons. 

Failed to install add-on
The command '/bin/sh -c go install github.com/bemasher/rtlamr@latest && apt-get update && apt-get install -y libusb-1.0-0-dev build-essential git cmake && git clone git://git.osmocom.org/rtl-sdr.git && cd rtl-sdr && mkdir build && cd build && cmake .. -DDETACH_KERNEL_DRIVER=ON -DENABLE_ZEROCOPY=ON -Wno-dev && make && make install' returned a non-zero code: 100

Log file entry:
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:123
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 1:44:27 PM (3 occurrences)
Last logged: 1:55:10 PM

Failed to to call /addons/6713e36e_rtlamr2mqtt/install - The command '/bin/sh -c go install github.com/bemasher/rtlamr@latest && apt-get update && apt-get install -y libusb-1.0-0-dev build-essential git cmake && git clone git://git.osmocom.org/rtl-sdr.git && cd rtl-sdr && mkdir build && cd build && cmake .. -DDETACH_KERNEL_DRIVER=ON -DENABLE_ZEROCOPY=ON -Wno-dev && make && make install' returned a non-zero code: 100

**Comment by allangood** [comment]
Without the full output is not possible to help.
This can be related to out of space on your machine.
