### ISSUE TITLE
900i sleep recommendation [FYI] Documentation

### ISSUE THREAD

**Issue by Nerdtality** [allangood/rtlamr2mqtt#175]
For 900i units, they only broadcast information every 7.5 mins so 420 sec sleep works perfectly. Not so sure about 900, but they are probably the same. I have an entire manual that goes into detail about these things.

**Comment by allangood** [comment]
Thank you for the info!

**Comment by cybergrimes** [comment]
@Nerdtality can you share a copy of this manual you mentioned?

**Comment by Nerdtality** [comment]
[publication_e-coderr900i-10.15.pdf](https://github.com/allangood/rtlamr2mqtt/files/10670851/publication_e-coderr900i-10.15.pdf)

Here it is, also I changed the 420 seconds to 450 for slightly better reliability.
