### ISSUE TITLE
possible documentation issue for docker-compose config

### ISSUE THREAD

**Issue by tehbra1n** [allangood/rtlamr2mqtt#2]
Using the current sample docker-compose.yml file, I get an error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.rtlamr.volumes contains an invalid type, it should be an array
```

I replaced the volumes section with:

```
    volumes:
      - '/etc/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro'
```

to resolve the error.  Docker isn't my area of expertise so I might be missing something, but I wanted to report it.

**Comment by allangood** [comment]
Hello @tehbra1n , thank you for your contribution!
Yes, there is a typo in the README file. The volume needs a "-" before the volume definition.

Thank you!
