### ISSUE TITLE
Reading 433MHz sensors?

### ISSUE THREAD

**Issue by bob-u** [allangood/rtlamr2mqtt#209]
Is it possible to read 433MHz sensors (temperature, humidity) with same SDR dongle when rtlamr2mqtt is installed?

**Comment by maxperron** [comment]
Following, I have the same question. I would like to also use my antenna to listen to a weather station.

**Comment by allangood** [comment]
In theory, yes it is possible. But every software will try to use and lock the USB device and/or change the frequency used for some specific purpose.

Ideally you should use one device for each frequency/application.
