### ISSUE TITLE
Unable to install from HACS

### ISSUE THREAD

**Issue by justin654** [allangood/rtlamr2mqtt#220]
I've reset my HA installation on a NUC, however I am unable to install this add on. I get an error message. Everything else has installed without a hitch. Anyone have any suggestions? 

Issue occuring on Home Assistant version 2023.11.3, also on 2023.12.0

Failed to install add-on
The command '/bin/sh -c go install github.com/bemasher/rtlamr@latest && apt-get update && apt-get install -y libusb-1.0-0-dev build-essential git cmake && git clone git://git.osmocom.org/rtl-sdr.git && cd rtl-sdr && mkdir build && cd build && cmake .. -DDETACH_KERNEL_DRIVER=ON -DENABLE_ZEROCOPY=ON -Wno-dev && make && make install' returned a non-zero code: 128

**Comment by justin654** [comment]
@allangood Any chance you have this issue on your radar already?

**Comment by justin654** [comment]
> I too have the same issue when trying to install on a RPi 4, but going through the add-on store after adding the repository.

If you are still having this issue, you can give this change a shot #221 it resolved the issue for me.

**Comment by MikeDembek** [comment]
I'm seeing this issue as well

**Comment by justin654** [comment]
> I'm seeing this issue as well

Try giving the fix I posted above, worked for me. #221

**Comment by allangood** [comment]
#221 was merged. Thank you @justin654 for your submission!

**Comment by MikeDembek** [comment]
That sorted it for me as well - thanks!

**Comment by allangood** [comment]
Awesome! Let's close this issue then!
Thank you for all your reports and feedback!
