### ISSUE TITLE
Readme: all msg types in listen mode

### ISSUE THREAD

**Issue by brianlow** [allangood/rtlamr2mqtt#40]
Suggest changing the LISTEN_ONLY sample command to listen for `all` message types since the sentence above says to use it when you don't know the protocol

```
docker run --rm -ti -e LISTEN_ONLY=yes -e RTL_MSGTYPE="all" --device=/dev/bus/usb:/dev/bus/usb allangood/rtlamr2mqtt
                                                       ^^^ 
```

**Comment by allangood** [comment]
Thank you for this note! I m going to update the README file!
