### ISSUE TITLE
Configuration file cannot be found at "/etc/rtlamr2mqtt.yaml" at startup of v1.5.1 

### ISSUE THREAD

**Issue by drmulligan** [allangood/rtlamr2mqtt#52]
After upgrading to v1.5.1 of the addon my meters report "unavailable."

The only log line is **Configuration file cannot be found at "/etc/rtlamr2mqtt.yaml"**

**Comment by jcollas** [comment]
The Dockerfile in rtlamr2mqtt/rtlamr2mqtt-addon/Dockerfile  the add on needs to be changed:

From 

FROM allangood/rtlamr2mqtt

CMD ["/usr/bin/rtlamr2mqtt.py", "/data/options.json"]

To

FROM allangood/rtlamr2mqtt

ENTRYPOINT ["/usr/bin/rtlamr2mqtt.py", "/data/options.json"]

Then rebuild the add-on in your HomeAssistant instance.  Worked for me.

**Comment by allangood** [comment]
Thank you @jcollas , I am sending this change right now!

**Comment by drmulligan** [comment]
Works now. Thank you.
