### ISSUE TITLE
Docker build failure

### ISSUE THREAD

**Issue by jonpaterson** [allangood/rtlamr2mqtt#8]
`WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.1.2; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Connecting to github.com (140.82.114.4:443)
wget: server returned error: HTTP/1.1 404 Not Found
The command '/bin/sh -c apk update     && apk add rtl-sdr     && pip3 install -r /tmp/requirements.txt     && chmod 755 /usr/bin/rtlamr2mqtt.py     && case ${TARGETPLATFORM} in          "linux/amd64")  ARCH=amd64  ;;          "linux/arm64")  ARCH=arm64  ;;          "linux/arm/v7") ARCH=arm    ;;          "linux/arm/v6") ARCH=arm    ;;          "linux/386")    ARCH=i386   ;;     esac     && wget https://github.com/bemasher/rtlamr/releases/download/${RTLAMR_VERSION}/rtlamr_linux_${ARCH}.tar.gz     && tar zxvf rtlamr_linux_${ARCH}.tar.gz     && chmod 755 rtlamr     && mv rtlamr /usr/bin     && rm -f /tmp/*' returned a non-zero code: 1`

**Comment by allangood** [comment]
This container is meant to be build using docker buildx like this:
```
docker buildx build --platform=linux/amd64 -t rtlamr2mqtt .
```
